/* Cloudflare Worker: public MCP server for Mgroup (mgroupweb.com/mcp via nginx proxy, or *.workers.dev).
   Transport: MCP streamable HTTP, stateless (POST JSON-RPC 2.0, JSON responses; no SSE stream, no sessions).
   Tools/data: worker/mcp-tools.js + worker/mcp-data.js (generated by _build/build_agent_files.py).
   Bindings: RL (rate limit), METRICS (service binding to mgroup-metrics for check_domain_authority). Deploy: worker/deploy-mcp.sh
*/
import { VERSION, SITE, INSTRUCTIONS, TOOLS, SERVER_CARD } from './mcp-tools.js';
import { CHECKLIST, SNIPPETS } from './mcp-data.js';

const SUPPORTED = ['2025-06-18', '2025-03-26', '2024-11-05'];
const ORIGIN_IPS = ['164.92.211.78']; // our nginx proxy: trust its X-Real-IP
const SUBTYPES = { services: 'cpt_services', guides: 'cpt_blogs', case_studies: 'cpt_casestudies', pages: 'page', any: 'cpt_services,cpt_blogs,cpt_casestudies,page' };
const TYPE_LABEL = { cpt_services: 'service', cpt_blogs: 'guide', cpt_casestudies: 'case study', page: 'page' };
const MEMO = new Map();

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Accept, Authorization, Mcp-Session-Id, Mcp-Protocol-Version',
  'Access-Control-Expose-Headers': 'Mcp-Session-Id, Mcp-Protocol-Version',
  'Access-Control-Max-Age': '86400',
};

export default {
  async fetch(req, env, ctx) {
    const url = new URL(req.url);
    const path = url.pathname.replace(/\/+$/, '') || '/';
    if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });

    if (path === '/mcp/server-card' || path === '/.well-known/mcp/server-card.json' || path === '/.well-known/mcp.json') {
      return new Response(JSON.stringify(SERVER_CARD, null, 2), { headers: { ...CORS, 'Content-Type': 'application/mcp-server-card+json; charset=utf-8', 'Cache-Control': 'public, max-age=3600' } });
    }
    if (path === '/' || path === '/mcp/info') {
      return json({ name: SERVER_CARD.serverInfo.name, version: VERSION, mcp_endpoint: SERVER_CARD.transport.endpoint, server_card: SERVER_CARD.transport.endpoint + '/server-card', tools: TOOLS.map(t => t.name), docs: SITE + '/auth.md' });
    }
    if (path !== '/mcp') return json({ error: 'not found' }, 404);
    if (req.method === 'GET' || req.method === 'HEAD') {
      if (/text\/html/i.test(req.headers.get('Accept') || '')) return new Response(infoPage(), { headers: { ...CORS, 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex' } });
      return json({ error: 'method_not_allowed', message: 'This MCP server is stateless: send JSON-RPC 2.0 requests with POST to this URL (Streamable HTTP transport). No SSE stream is offered on GET.', endpoint: SERVER_CARD.transport.endpoint, server_card: SERVER_CARD.transport.endpoint + '/server-card', docs: SITE + '/auth.md' }, 405, { Allow: 'POST, OPTIONS', 'Cache-Control': 'no-store' });
    }
    if (req.method !== 'POST') return json({ error: 'method not allowed' }, 405, { Allow: 'POST, OPTIONS' });

    let body;
    try { body = await req.json(); } catch { return json(rpcError(null, -32700, 'Parse error'), 400); }
    const batch = Array.isArray(body);
    const msgs = batch ? body : [body];
    if (!msgs.length) return json(rpcError(null, -32600, 'Invalid Request'), 400);

    const ip = clientIp(req);
    const results = [];
    for (const m of msgs) {
      if (!m || m.jsonrpc !== '2.0' || typeof m.method !== 'string') { results.push(rpcError(m && m.id !== undefined ? m.id : null, -32600, 'Invalid Request')); continue; }
      if (m.id === undefined || m.id === null) continue; // notification (e.g. notifications/initialized)
      results.push(await handle(m, env, ip));
    }
    if (!results.length) return new Response(null, { status: 202, headers: CORS });
    return json(batch ? results : results[0]);
  },
};

async function handle(m, env, ip) {
  const p = m.params || {};
  try {
    switch (m.method) {
      case 'initialize': {
        const pv = SUPPORTED.includes(p.protocolVersion) ? p.protocolVersion : SUPPORTED[0];
        return rpcResult(m.id, { protocolVersion: pv, capabilities: { tools: { listChanged: false } }, serverInfo: { name: SERVER_CARD.serverInfo.name, title: SERVER_CARD.serverInfo.title, version: VERSION }, instructions: INSTRUCTIONS });
      }
      case 'ping': return rpcResult(m.id, {});
      case 'tools/list': return rpcResult(m.id, { tools: TOOLS });
      case 'tools/call': {
        const tool = TOOLS.find(t => t.name === p.name);
        if (!tool) return rpcError(m.id, -32602, `Unknown tool: ${p.name}`);
        if (env.RL) {
          const { success } = await env.RL.limit({ key: 'mcp:' + ip });
          if (!success) return rpcResult(m.id, { content: [{ type: 'text', text: 'Rate limit: 30 tool calls per minute per IP. Please retry shortly.' }], isError: true });
        }
        const out = await callTool(p.name, p.arguments || {}, env, ip);
        return rpcResult(m.id, out);
      }
      case 'resources/list': return rpcResult(m.id, { resources: [] });
      case 'prompts/list': return rpcResult(m.id, { prompts: [] });
      default: return rpcError(m.id, -32601, `Method not found: ${m.method}`);
    }
  } catch (e) {
    return rpcError(m.id, -32603, 'Internal error: ' + (e && e.message ? e.message : String(e)));
  }
}

async function callTool(name, a, env, ip) {
  switch (name) {
    case 'search_mgroupweb': return searchSite(a);
    case 'read_mgroupweb_page': return readPage(a);
    case 'list_shopify_services': return listServices();
    case 'estimate_shopify_plus_cost': return plusCost(a);
    case 'shopify_migration_checklist': return checklist(a);
    case 'shopify_liquid_snippet': return snippet(a);
    case 'check_domain_authority': return domainAuthority(a, env, ip);
  }
  return text('Unknown tool', true);
}

// ---------------------------------------------------------------- tools
async function searchSite(a) {
  const q = String(a.query || '').trim().slice(0, 200);
  if (!q) return text('query is required', true);
  const subtype = SUBTYPES[a.type] || SUBTYPES.any;
  const limit = Math.min(Math.max(parseInt(a.limit, 10) || 5, 1), 10);
  const u = `${SITE}/wp-json/wp/v2/search?search=${encodeURIComponent(q)}&per_page=${limit}&subtype=${subtype}&_fields=id,title,url,subtype`;
  const rows = await getJson(u, 300);
  if (!Array.isArray(rows)) return text('Search unavailable right now.', true);
  if (!rows.length) return text(`No results on mgroupweb.com for "${q}". Try a broader phrase or list_shopify_services.`);
  const lines = rows.map((r, i) => `${i + 1}. ${decode(r.title)} (${TYPE_LABEL[r.subtype] || r.subtype})\n   ${r.url}`);
  return { content: [{ type: 'text', text: `Results for "${q}":\n\n${lines.join('\n')}\n\nUse read_mgroupweb_page with a URL to read the full page.` }], structuredContent: { results: rows.map(r => ({ title: decode(r.title), url: r.url, type: TYPE_LABEL[r.subtype] || r.subtype })) } };
}

async function readPage(a) {
  let u;
  try { u = new URL(String(a.url || '')); } catch { return text('url must be an absolute URL on https://mgroupweb.com/', true); }
  if (!/^(www\.)?mgroupweb\.com$/.test(u.hostname) || u.protocol !== 'https:') return text('Only https://mgroupweb.com/ URLs can be read.', true);
  u.hostname = 'mgroupweb.com'; u.search = ''; u.hash = '';
  const max = Math.min(Math.max(parseInt(a.max_chars, 10) || 12000, 1000), 40000);
  const key = 'md:' + u.href;
  let md = memoGet(key);
  if (!md) {
    const r = await fetch(u.href, { headers: { Accept: 'text/markdown', 'User-Agent': 'mgroup-mcp/' + VERSION }, cf: { cacheTtl: 0 } });
    if (r.status === 404) return text(`Page not found: ${u.href}`, true);
    if (!r.ok) return text(`Could not fetch ${u.href} (HTTP ${r.status}).`, true);
    md = await r.text();
    if (!/markdown/i.test(r.headers.get('content-type') || '')) md = htmlToText(md);
    memoSet(key, md, 600);
  }
  const clipped = md.length > max ? md.slice(0, max) + `\n\n[truncated at ${max} of ${md.length} characters; call again with a larger max_chars]` : md;
  return { content: [{ type: 'text', text: clipped }] };
}

async function listServices() {
  const rows = await getJson(`${SITE}/wp-json/wp/v2/cpt_services?per_page=50&_fields=title,link`, 3600);
  if (!Array.isArray(rows) || !rows.length) return text('Service list unavailable right now; see ' + SITE + '/services/', true);
  const lines = rows.map(r => `- ${decode(r.title && r.title.rendered)} — ${r.link}`);
  return { content: [{ type: 'text', text: `Mgroup Shopify services (${rows.length}):\n${lines.join('\n')}\n\nHub: ${SITE}/services/ · Engagement models: ${SITE}/shopify-engagement-models/ · Quote: ${SITE}/grow-ecommerce-business/` }], structuredContent: { services: rows.map(r => ({ title: decode(r.title && r.title.rendered), url: r.link })) } };
}

function plusCost(a) {
  const g = num(a.monthly_revenue);
  if (!(g >= 0)) return text('monthly_revenue (USD) is required', true);
  const base = a.contract_term === '1-year' ? 2500 : 2300;
  const gwRate = a.gateway === 'third_party' ? 0.002 : 0;
  const variable = Math.min(g * 0.0025, 40000);
  const platform = Math.max(base, variable);
  const mode = variable > base ? (variable >= 40000 ? '$40,000 cap' : '0.25% revenue model') : `flat $${base.toLocaleString('en-US')} base`;
  const gateway = g * gwRate, apps = num(a.apps_monthly), dev = num(a.dev_monthly), mig = num(a.migration_one_off);
  const monthly = platform + gateway + apps + dev, yearly = monthly * 12, year1 = yearly + mig;
  const f = n => '$' + Math.round(n).toLocaleString('en-US');
  const lines = [
    `Shopify Plus cost estimate (reference figures — confirm current terms with Shopify)`,
    `Monthly revenue: ${f(g)}`,
    `Platform fee: ${f(platform)}/mo (${mode})`,
    `Third-party gateway fee: ${f(gateway)}/mo`,
    `Apps: ${f(apps)}/mo`,
    `Development & maintenance: ${f(dev)}/mo`,
    `Monthly all-in: ${f(monthly)}`,
    `Ongoing per year: ${f(yearly)}`,
    `One-off migration & integrations: ${f(mig)}`,
    `Year one TCO: ${f(year1)}`,
    `Platform fee as % of revenue: ${g ? (platform / g * 100).toFixed(2) + '%' : 'n/a'}`,
    `Versus the ~$399/mo Advanced plan the platform fee is ${f(platform - 399)}/mo higher (${f((platform - 399) * 12)}/yr) before counting checkout extensibility, native B2B, Shopify Functions, Flow, Launchpad and expansion stores.`,
    `Source: ${SITE}/blogs/shopify-plus-pricing-cost/ · Calculator: https://mgroupweb.github.io/shopify-plus-pricing-calculator/`,
  ];
  return { content: [{ type: 'text', text: lines.join('\n') }], structuredContent: { monthly_revenue: g, base_fee: base, platform_fee: platform, mode, gateway_fee: gateway, apps, dev, monthly_total: monthly, yearly_total: yearly, migration_one_off: mig, year_one_tco: year1 } };
}

function checklist(a) {
  const n = parseInt(a.phase, 10);
  const phases = n >= 1 && n <= CHECKLIST.length ? [CHECKLIST[n - 1]] : CHECKLIST;
  const out = phases.map(p => { const i = CHECKLIST.indexOf(p) + 1; return `## Phase ${i}: ${p.title}\n${p.desc}\n${p.tasks.map(t => '- [ ] ' + t).join('\n')}`; });
  return { content: [{ type: 'text', text: `Shopify migration checklist by Mgroup (${SITE}/services/shopify-migration-experts/)\n\n${out.join('\n\n')}\n\nInteractive version: https://mgroupweb.github.io/shopify-migration-checklist/` }] };
}

function snippet(a) {
  const id = String(a.id || '').trim();
  if (!id) return { content: [{ type: 'text', text: 'Available Liquid snippets:\n' + SNIPPETS.map(s => `- ${s.id}: ${s.title} (${s.file}; ${s.tags.join(', ')})`).join('\n') }] };
  const s = SNIPPETS.find(x => x.id === id);
  if (!s) return text(`Unknown snippet id "${id}". Known: ${SNIPPETS.map(x => x.id).join(', ')}`, true);
  return { content: [{ type: 'text', text: `${s.title}\nFile: ${s.file}\n${s.desc}\n\n\`\`\`liquid\n${s.code.join('\n')}\n\`\`\`\nSource: https://mgroupweb.github.io/shopify-liquid-snippets/#${s.id}` }] };
}

async function domainAuthority(a, env, ip) {
  const domains = [...new Set((Array.isArray(a.domains) ? a.domains : [a.domains]).map(normalize).filter(Boolean))].slice(0, 5);
  if (!domains.length) return text('domains[] is required', true);
  if (!env.METRICS) return text('Metrics backend not configured.', true);
  const r = await env.METRICS.fetch('https://mgroup-metrics/', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://mgroupweb.github.io', 'CF-Connecting-IP': ip }, body: JSON.stringify({ domains }) });
  let d; try { d = await r.json(); } catch { d = null; }
  if (!r.ok || !d || d.error) return text('Metrics unavailable: ' + (d && d.error ? d.error : 'HTTP ' + r.status), true);
  const metrics = d.metrics || {};
  const rows = domains.map(dom => {
    const m = metrics[dom] || {};
    const v = k => (m[k] === null || m[k] === undefined ? '—' : m[k]);
    const radar = m.radarBucket ? `top ${Number(m.radarBucket).toLocaleString('en-US')}` : '—';
    return `${dom}: Moz DA ${v('da')} · PA ${v('pa')} · Spam Score ${v('spam')}% · Open PageRank ${v('opr')}/10 · Cloudflare Radar ${radar}` + (m.dr != null ? ` · Ahrefs DR ${m.dr}` : '');
  });
  const note = d.notice ? `\n(${d.notice})` : '';
  return { content: [{ type: 'text', text: rows.join('\n') + note + '\nFree checker with Tranco authority, age and HTTPS: https://mgroupweb.github.io/#authority' }], structuredContent: { metrics: Object.fromEntries(domains.map(dom => [dom, metrics[dom] || null])), status: d.status || null } };
}

// ---------------------------------------------------------------- browser landing for GET /mcp
function infoPage() {
  const ep = SERVER_CARD.transport.endpoint;
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const tools = TOOLS.map(t => `<li><code>${esc(t.name)}</code> — ${esc(t.description)}</li>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Mgroup MCP server</title>
<style>body{margin:0;background:#1F2544;color:#fff;font:16px/1.6 Inter,system-ui,sans-serif}main{max-width:760px;margin:0 auto;padding:56px 24px}h1{font-size:32px;margin:0 0 8px}h2{font-size:20px;margin:36px 0 12px}p{margin:0 0 14px;color:#cfd3e6}a{color:#40D0FF}code,pre{font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}pre{background:#151a33;border:1px solid rgba(64,208,255,.25);border-radius:10px;padding:16px;overflow:auto;color:#e6e8f5}ul{padding-left:20px;color:#cfd3e6}li{margin:6px 0}.pill{display:inline-block;padding:3px 10px;border-radius:999px;background:rgba(64,208,255,.14);color:#40D0FF;font-size:13px;font-weight:600;margin-bottom:18px}.foot{margin-top:40px;font-size:14px;color:#9aa0bf}</style></head><body><main>
<span class="pill">Model Context Protocol · public · no auth</span>
<h1>Mgroup MCP server</h1>
<p>${esc(SERVER_CARD.serverInfo.description)} Endpoint: <code>${esc(ep)}</code> (Streamable HTTP, JSON-RPC 2.0 over POST). Server card: <a href="${esc(ep)}/server-card">${esc(ep)}/server-card</a>.</p>
<h2>Connect</h2>
<p><strong>Claude Desktop / Claude Code</strong></p><pre>claude mcp add --transport http mgroup ${esc(ep)}</pre>
<p><strong>ChatGPT</strong>: Settings → Connectors → Add → MCP server URL <code>${esc(ep)}</code>, authentication: none.</p>
<p><strong>Cursor / Windsurf / any MCP client</strong></p><pre>{ "mcpServers": { "mgroup": { "url": "${esc(ep)}" } } }</pre>
<p><strong>curl</strong></p><pre>curl -X POST ${esc(ep)} -H 'Content-Type: application/json' \\
  -d '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'</pre>
<h2>Tools</h2><ul>${tools}</ul>
<p class="foot">Rate limit 30 tool calls per minute per IP. Public content only; nothing is written to mgroupweb.com. Access notes: <a href="${esc(SITE)}/auth.md">${esc(SITE)}/auth.md</a> · Agent skills: <a href="${esc(SITE)}/.well-known/agent-skills/index.json">/.well-known/agent-skills/index.json</a> · <a href="${esc(SITE)}/">mgroupweb.com</a></p>
</main></body></html>`;
}

// ---------------------------------------------------------------- helpers
function text(t, isError) { const o = { content: [{ type: 'text', text: t }] }; if (isError) o.isError = true; return o; }
function rpcResult(id, result) { return { jsonrpc: '2.0', id, result }; }
function rpcError(id, code, message) { return { jsonrpc: '2.0', id, error: { code, message } }; }
function json(o, status = 200, extra = {}) { return new Response(JSON.stringify(o), { status, headers: { ...CORS, 'Content-Type': 'application/json; charset=utf-8', ...extra } }); }
function num(v) { const n = parseFloat(v); return isFinite(n) && n >= 0 ? n : 0; }
function normalize(s) { return String(s || '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').split(/[/?#]/)[0]; }
function decode(s) { return String(s || '').replace(/&#(\d+);/g, (_, n) => String.fromCharCode(n)).replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#8211;|&ndash;/g, '–').replace(/&#8217;/g, '’').replace(/<[^>]+>/g, ''); }
function htmlToText(h) { return h.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, '').replace(/<[^>]+>/g, ' ').replace(/\s{2,}/g, ' ').trim(); }
function clientIp(req) {
  const cf = req.headers.get('CF-Connecting-IP') || '';
  if (ORIGIN_IPS.includes(cf)) return req.headers.get('X-Real-IP') || req.headers.get('X-Forwarded-For')?.split(',')[0].trim() || cf;
  return cf || 'x';
}
function memoGet(k) { const v = MEMO.get(k); if (v && v.exp > Date.now()) return v.val; MEMO.delete(k); return null; }
function memoSet(k, val, ttl) { if (MEMO.size > 200) MEMO.clear(); MEMO.set(k, { val, exp: Date.now() + ttl * 1000 }); }
async function getJson(u, ttl) {
  const c = memoGet('j:' + u); if (c) return c;
  try {
    const r = await fetch(u, { headers: { Accept: 'application/json', 'User-Agent': 'mgroup-mcp/' + VERSION } });
    if (!r.ok) return null;
    const d = await r.json(); memoSet('j:' + u, d, ttl); return d;
  } catch { return null; }
}
