// Generated by _build/build_agent_files.py from _build/data — do not edit by hand.
export const CHECKLIST = [
 {
  "title": "Pre-migration audit",
  "desc": "Every Shopify migration project starts with a full data transfer audit. Baseline everything you will compare against after launch. Read: Shopify SEO migration.",
  "tasks": [
   "Crawl the current site (Screaming Frog or similar) and export every indexable URL",
   "Export Google Search Console performance: top pages, queries, clicks and impressions for the last 12 months",
   "Record Analytics baselines: revenue, conversion rate, AOV, traffic by channel",
   "Document current theme features, custom code and third-party scripts",
   "List all apps, plugins and integrations with their owners and costs",
   "Inventory payment gateways, shipping rules, tax settings and currencies",
   "Take a full backup of the legacy database and media library",
   "Define the migration scope, timeline, freeze window and stakeholders"
  ]
 },
 {
  "title": "Data inventory & export",
  "desc": "A standard migration includes products, customers, orders, SEO metadata, content pages, blog posts, reviews and discount codes. Customer passwords cannot be migrated.",
  "tasks": [
   "Export products with variants, options, SKUs, barcodes, weights and inventory",
   "Export product images with alt text; map file names to handles",
   "Export categories/collections and product-to-collection assignments",
   "Export customers with addresses, tags, marketing consent and company data (B2B)",
   "Export order history with line items, fulfilment and payment status",
   "Export reviews (with product mapping) and discount codes",
   "Export blog posts, CMS pages and legal pages with publish dates",
   "Map legacy attributes to Shopify metafields and define them in Custom data",
   "Plan the customer password-reset email for first login after launch"
  ]
 },
 {
  "title": "SEO preservation plan",
  "desc": "We implement 301 redirects, map legacy URLs and carry over vital data so you do not lose rankings. URL formats differ per platform, so mapping is never one-to-one.",
  "tasks": [
   "Build the URL map: legacy URL \u2192 new Shopify URL for products, collections, pages, blog posts",
   "Prepare 301 redirects (bulk import in Shopify Navigation \u2192 URL redirects)",
   "Carry over meta titles, descriptions and image alt text",
   "Recreate canonical logic for filtered/paginated collection pages",
   "Port structured data (Product, Organization, Breadcrumb, FAQ) into the theme",
   "Plan hreflang and Shopify Markets setup for multi-region stores",
   "Preserve internal linking in migrated content (rewrite absolute legacy links)",
   "Keep robots.txt and sitemap behaviour aligned with the legacy site"
  ]
 },
 {
  "title": "Theme & storefront rebuild",
  "desc": "We rebuild your store on Shopify with better architecture and faster performance \u2014 Online Store 2.0 sections and blocks, targeting 90+ Lighthouse scores. See Shopify theme development.",
  "tasks": [
   "Choose the approach: custom theme, customised base theme, or Hydrogen/headless",
   "Rebuild templates: home, collection, product, cart, search, blog, pages, 404",
   "Recreate navigation, mega menu and footer structure",
   "Implement filters and sorting (Search & Discovery app or custom)",
   "Recreate custom features as sections/blocks \u2014 no hard-coded content",
   "Set up product templates and metafield-driven content blocks",
   "Optimise images, fonts and scripts for Core Web Vitals",
   "Configure translations and localisation (Translate & Adapt or app)"
  ]
 },
 {
  "title": "Apps & integrations",
  "desc": "App data moves too: a Klaviyo migration keeps flows, segments and profiles intact, and Recharge subscription contracts transfer without re-billing customers. Enterprise builds need ERP, PIM, CRM and 3PL connections.",
  "tasks": [
   "Replace each legacy plugin with a Shopify-native feature, app or custom code",
   "Migrate email marketing (Klaviyo): profiles, segments, flows and templates",
   "Migrate subscriptions (Recharge or Shopify Subscriptions) without re-billing",
   "Connect ERP / PIM / CRM / 3PL via Admin API, Flow or middleware",
   "Set up reviews, loyalty, search, analytics and support apps",
   "Install GA4, GTM, Meta Pixel and server-side tracking via Customer Events",
   "Rebuild B2B: company accounts, catalogs, price lists and net terms (Plus)",
   "Document every webhook and API integration with an owner"
  ]
 },
 {
  "title": "Payments, taxes & shipping",
  "desc": "Default to Shopify Payments unless you have a compelling reason not to \u2014 it avoids the extra third-party gateway fee. Model this in the Shopify Plus pricing calculator.",
  "tasks": [
   "Activate Shopify Payments (or configure the third-party gateway) and test payouts",
   "Enable wallets: Shop Pay, Apple Pay, Google Pay, PayPal",
   "Configure taxes, VAT/GST registrations and tax-inclusive pricing per market",
   "Recreate shipping zones, rates, carrier accounts and local delivery/pickup",
   "Set up currencies and Shopify Markets pricing rules",
   "Configure checkout: branding, extensions, upsells, order notes",
   "Recreate discount rules and automatic discounts; import codes",
   "Set up gift cards and store credit if used"
  ]
 },
 {
  "title": "Testing & QA",
  "desc": "Test with real data before launch. We perform SEO audits before and after launch so rankings hold.",
  "tasks": [
   "Run a full import on a test store and validate counts (products, variants, customers, orders)",
   "Spot-check 50 random products: price, images, variants, inventory, metafields",
   "Test every 301 redirect from the URL map (automated crawl)",
   "Place test orders on every payment method and shipping scenario",
   "Test customer accounts, password reset and order history visibility",
   "Cross-browser and mobile QA on templates and checkout",
   "Run Lighthouse / Core Web Vitals on key templates",
   "Validate structured data and meta tags with Rich Results Test",
   "Review accessibility basics: contrast, focus states, alt text, keyboard navigation"
  ]
 },
 {
  "title": "Launch & cutover",
  "desc": "Zero-downtime cutover: lower DNS TTL in advance, freeze content on the legacy platform, run a final delta sync, then switch. Guide: zero-downtime migration.",
  "tasks": [
   "Lower DNS TTL 24\u201348 hours before launch",
   "Announce the content and order freeze window to all teams",
   "Run the final delta migration: new orders, customers and inventory changes",
   "Connect the domain in Shopify and verify SSL",
   "Point DNS to Shopify; keep the legacy site reachable on a temporary host",
   "Remove the password page and check robots/indexing settings",
   "Submit the new sitemap in Google Search Console and Bing Webmaster Tools",
   "Send the customer password-reset / welcome email campaign"
  ]
 },
 {
  "title": "Post-launch monitoring",
  "desc": "After launch, we stay. Monitor 404s, rankings, speed and conversion for at least 30 days and fix redirect gaps quickly. Ongoing help: on-demand Shopify support.",
  "tasks": [
   "Monitor Search Console for 404s, crawl errors and coverage drops daily for two weeks",
   "Compare rankings and organic traffic against the pre-migration baseline",
   "Watch conversion rate, AOV and checkout abandonment vs baseline",
   "Fix missing redirects and broken internal links as they surface",
   "Confirm integrations (ERP, 3PL, email, subscriptions) are syncing correctly",
   "Re-run Lighthouse and fix any performance regressions",
   "Decommission the legacy platform after 30\u201360 days of clean data",
   "Schedule a post-launch CRO review"
  ]
 }
];
export const SNIPPETS = [
 {
  "id": "section-schema",
  "title": "Online Store 2.0 section skeleton with blocks",
  "file": "sections/mg-feature-grid.liquid",
  "tags": [
   "sections",
   "theme"
  ],
  "desc": "Minimal section with settings, repeatable blocks and presets so it appears in the theme editor. Start every custom Shopify section from here.",
  "code": [
   "{%- comment -%} sections/mg-feature-grid.liquid {%- endcomment -%}",
   "<section class=\"mg-feature-grid\" id=\"shopify-section-{{ section.id }}\">",
   "  {%- if section.settings.heading != blank -%}",
   "    <h2 class=\"mg-feature-grid__title\">{{ section.settings.heading | escape }}</h2>",
   "  {%- endif -%}",
   "  <div class=\"mg-feature-grid__items\">",
   "    {%- for block in section.blocks -%}",
   "      <div class=\"mg-feature-grid__item\" {{ block.shopify_attributes }}>",
   "        {%- if block.settings.icon != blank -%}",
   "          {{ block.settings.icon | image_url: width: 96 | image_tag: loading: 'lazy', widths: '48, 96', alt: block.settings.title }}",
   "        {%- endif -%}",
   "        <h3>{{ block.settings.title | escape }}</h3>",
   "        <div class=\"rte\">{{ block.settings.text }}</div>",
   "      </div>",
   "    {%- endfor -%}",
   "  </div>",
   "</section>",
   "",
   "{% schema %}",
   "{",
   "  \"name\": \"Feature grid\",",
   "  \"tag\": \"section\",",
   "  \"class\": \"section\",",
   "  \"settings\": [",
   "    { \"type\": \"text\", \"id\": \"heading\", \"label\": \"Heading\", \"default\": \"Why shop with us\" }",
   "  ],",
   "  \"blocks\": [",
   "    {",
   "      \"type\": \"feature\",",
   "      \"name\": \"Feature\",",
   "      \"limit\": 6,",
   "      \"settings\": [",
   "        { \"type\": \"image_picker\", \"id\": \"icon\", \"label\": \"Icon\" },",
   "        { \"type\": \"text\", \"id\": \"title\", \"label\": \"Title\", \"default\": \"Free shipping\" },",
   "        { \"type\": \"richtext\", \"id\": \"text\", \"label\": \"Text\", \"default\": \"<p>On all orders over $50.</p>\" }",
   "      ]",
   "    }",
   "  ],",
   "  \"presets\": [{ \"name\": \"Feature grid\", \"blocks\": [{ \"type\": \"feature\" }, { \"type\": \"feature\" }, { \"type\": \"feature\" }] }]",
   "}",
   "{% endschema %}"
  ]
 },
 {
  "id": "free-shipping-bar",
  "title": "Free shipping progress bar for the cart",
  "file": "snippets/mg-shipping-bar.liquid",
  "tags": [
   "cart",
   "cro"
  ],
  "desc": "Shows how much is left to unlock free shipping. Threshold is a theme setting in cents-aware currency; call it with {% render 'mg-shipping-bar', threshold: settings.free_shipping_threshold %}. A classic CRO win for AOV.",
  "code": [
   "{%- comment -%} snippets/mg-shipping-bar.liquid \u2014 threshold in store currency units {%- endcomment -%}",
   "{%- assign threshold_cents = threshold | times: 100 -%}",
   "{%- assign remaining = threshold_cents | minus: cart.total_price -%}",
   "{%- assign percent = cart.total_price | times: 100 | divided_by: threshold_cents | at_most: 100 -%}",
   "<div class=\"mg-shipping-bar\" role=\"status\" aria-live=\"polite\">",
   "  {%- if remaining > 0 -%}",
   "    <p class=\"mg-shipping-bar__text\">Add {{ remaining | money }} more for <strong>free shipping</strong></p>",
   "  {%- else -%}",
   "    <p class=\"mg-shipping-bar__text\">\ud83c\udf89 You've unlocked <strong>free shipping</strong></p>",
   "  {%- endif -%}",
   "  <div class=\"mg-shipping-bar__track\"><div class=\"mg-shipping-bar__fill\" style=\"width: {{ percent }}%\"></div></div>",
   "</div>"
  ]
 },
 {
  "id": "metafield-fallback",
  "title": "Product metafield with safe fallback",
  "file": "snippets/mg-metafield.liquid",
  "tags": [
   "product",
   "metafields"
  ],
  "desc": "Renders a metafield only when the definition exists and has a value; falls back to a default. Works for single-line text, rich text and lists.",
  "code": [
   "{%- comment -%} Single-line text or number {%- endcomment -%}",
   "{%- assign material = product.metafields.specs.material -%}",
   "{%- if material != blank -%}",
   "  <dt>Material</dt><dd>{{ material.value | escape }}</dd>",
   "{%- else -%}",
   "  <dt>Material</dt><dd>See product description</dd>",
   "{%- endif -%}",
   "",
   "{%- comment -%} Rich text (metafield_tag renders proper HTML) {%- endcomment -%}",
   "{%- if product.metafields.specs.care_guide != blank -%}",
   "  <div class=\"rte\">{{ product.metafields.specs.care_guide | metafield_tag }}</div>",
   "{%- endif -%}",
   "",
   "{%- comment -%} List of single-line text {%- endcomment -%}",
   "{%- if product.metafields.specs.features.value.size > 0 -%}",
   "  <ul>",
   "    {%- for feature in product.metafields.specs.features.value -%}",
   "      <li>{{ feature | escape }}</li>",
   "    {%- endfor -%}",
   "  </ul>",
   "{%- endif -%}"
  ]
 },
 {
  "id": "responsive-image",
  "title": "Responsive image with srcset and lazy loading",
  "file": "snippets/mg-image.liquid",
  "tags": [
   "performance",
   "theme"
  ],
  "desc": "Uses image_url + image_tag so Shopify serves the right size per viewport; first-fold images get loading: eager and fetchpriority for better LCP. Part of every performance audit we run.",
  "code": [
   "{%- comment -%} {% render 'mg-image', image: product.featured_image, sizes: '(min-width: 990px) 50vw, 100vw', eager: true %} {%- endcomment -%}",
   "{%- if image != blank -%}",
   "  {%- assign loading = 'lazy' -%}",
   "  {%- assign priority = 'auto' -%}",
   "  {%- if eager -%}{%- assign loading = 'eager' -%}{%- assign priority = 'high' -%}{%- endif -%}",
   "  {{ image",
   "    | image_url: width: 1800",
   "    | image_tag:",
   "        widths: '360, 540, 720, 900, 1080, 1296, 1512, 1800',",
   "        sizes: sizes | default: '100vw',",
   "        loading: loading,",
   "        fetchpriority: priority,",
   "        alt: image.alt | default: product.title | escape",
   "  }}",
   "{%- endif -%}"
  ]
 },
 {
  "id": "sale-badge",
  "title": "Sale badge with discount percentage",
  "file": "snippets/mg-sale-badge.liquid",
  "tags": [
   "product",
   "cro"
  ],
  "desc": "Computes the discount from compare_at_price for the selected variant and only renders when there is a real saving. Use money_without_trailing_zeros for cleaner prices.",
  "code": [
   "{%- assign v = product.selected_or_first_available_variant -%}",
   "{%- if v.compare_at_price > v.price -%}",
   "  {%- assign saving = v.compare_at_price | minus: v.price -%}",
   "  {%- assign percent = saving | times: 100 | divided_by: v.compare_at_price -%}",
   "  <span class=\"mg-badge mg-badge--sale\">Save {{ percent }}%</span>",
   "  <s class=\"mg-price__compare\">{{ v.compare_at_price | money_without_trailing_zeros }}</s>",
   "{%- endif -%}",
   "<span class=\"mg-price\">{{ v.price | money_without_trailing_zeros }}</span>"
  ]
 },
 {
  "id": "low-stock",
  "title": "Low-stock and sold-out badges",
  "file": "snippets/mg-stock-badge.liquid",
  "tags": [
   "product",
   "cro"
  ],
  "desc": "Urgency badge that respects inventory policy: sold out when unavailable, \"only N left\" under a threshold, silent otherwise. Threshold defaults to 5.",
  "code": [
   "{%- assign v = product.selected_or_first_available_variant -%}",
   "{%- assign low = low_threshold | default: 5 -%}",
   "{%- if v.available == false -%}",
   "  <span class=\"mg-badge mg-badge--soldout\">Sold out</span>",
   "{%- elsif v.inventory_management == 'shopify' and v.inventory_policy == 'deny' and v.inventory_quantity <= low -%}",
   "  <span class=\"mg-badge mg-badge--low\">Only {{ v.inventory_quantity }} left</span>",
   "{%- endif -%}"
  ]
 },
 {
  "id": "breadcrumbs",
  "title": "SEO breadcrumbs with BreadcrumbList JSON-LD",
  "file": "snippets/mg-breadcrumbs.liquid",
  "tags": [
   "seo",
   "theme"
  ],
  "desc": "Visible breadcrumbs plus matching structured data for product, collection, page and article templates. Uses the collection the customer came from when available. See our Shopify SEO services.",
  "code": [
   "{%- unless template == 'index' -%}",
   "{%- assign crumbs = '' -%}",
   "<nav class=\"mg-crumbs\" aria-label=\"Breadcrumb\"><ol>",
   "  <li><a href=\"{{ routes.root_url }}\">Home</a></li>",
   "  {%- case template.name -%}",
   "    {%- when 'product' -%}",
   "      {%- if collection -%}<li><a href=\"{{ collection.url }}\">{{ collection.title | escape }}</a></li>{%- endif -%}",
   "      <li aria-current=\"page\">{{ product.title | escape }}</li>",
   "    {%- when 'collection' -%}",
   "      <li aria-current=\"page\">{{ collection.title | escape }}</li>",
   "    {%- when 'article' -%}",
   "      <li><a href=\"{{ blog.url }}\">{{ blog.title | escape }}</a></li>",
   "      <li aria-current=\"page\">{{ article.title | escape }}</li>",
   "    {%- when 'page' -%}",
   "      <li aria-current=\"page\">{{ page.title | escape }}</li>",
   "  {%- endcase -%}",
   "</ol></nav>",
   "<script type=\"application/ld+json\">",
   "{",
   "  \"@context\": \"https://schema.org\",",
   "  \"@type\": \"BreadcrumbList\",",
   "  \"itemListElement\": [",
   "    { \"@type\": \"ListItem\", \"position\": 1, \"name\": \"Home\", \"item\": \"{{ shop.url }}{{ routes.root_url }}\" }",
   "    {%- if template.name == 'product' and collection -%},",
   "    { \"@type\": \"ListItem\", \"position\": 2, \"name\": {{ collection.title | json }}, \"item\": \"{{ shop.url }}{{ collection.url }}\" },",
   "    { \"@type\": \"ListItem\", \"position\": 3, \"name\": {{ product.title | json }}, \"item\": \"{{ shop.url }}{{ product.url }}\" }",
   "    {%- elsif template.name == 'product' -%},",
   "    { \"@type\": \"ListItem\", \"position\": 2, \"name\": {{ product.title | json }}, \"item\": \"{{ shop.url }}{{ product.url }}\" }",
   "    {%- elsif template.name == 'collection' -%},",
   "    { \"@type\": \"ListItem\", \"position\": 2, \"name\": {{ collection.title | json }}, \"item\": \"{{ shop.url }}{{ collection.url }}\" }",
   "    {%- endif -%}",
   "  ]",
   "}",
   "</script>",
   "{%- endunless -%}"
  ]
 },
 {
  "id": "product-json",
  "title": "Hand product data to JavaScript safely",
  "file": "sections/main-product.liquid",
  "tags": [
   "product",
   "javascript"
  ],
  "desc": "Emit variant data as JSON in a <script type=\"application/json\"> tag instead of inline JS \u2014 safe against quotes, cacheable, and easy to read in your variant picker.",
  "code": [
   "<script type=\"application/json\" id=\"mg-product-{{ section.id }}\">",
   "  {{ product | json }}",
   "</script>",
   "<script type=\"application/json\" id=\"mg-variants-{{ section.id }}\">",
   "  {{ product.variants | json }}",
   "</script>",
   "",
   "<script>",
   "  (function () {",
   "    var product = JSON.parse(document.getElementById('mg-product-{{ section.id }}').textContent);",
   "    var variants = JSON.parse(document.getElementById('mg-variants-{{ section.id }}').textContent);",
   "    // Example: find the variant matching selected options",
   "    function findVariant(options) {",
   "      return variants.find(function (v) {",
   "        return v.options.every(function (o, i) { return o === options[i]; });",
   "      });",
   "    }",
   "    window.mgProduct = { product: product, variants: variants, findVariant: findVariant };",
   "  })();",
   "</script>"
  ]
 }
];
